In [2]:
from sklearn.linear_model import LogisticRegression
from sklearn.svm import SVC
from sklearn.ensemble import RandomForestClassifier
import numpy as np 
import pandas as pd

In [30]:
df = pd.read_csv('IRIS.csv')
df

sepal_length  sepal_width  petal_length  petal_width         species
0             5.1          3.5           1.4          0.2     Iris-setosa
1             4.9          3.0           1.4          0.2     Iris-setosa
2             4.7          3.2           1.3          0.2     Iris-setosa
3             4.6          3.1           1.5          0.2     Iris-setosa
4             5.0          3.6           1.4          0.2     Iris-setosa
..            ...          ...           ...          ...             ...
145           6.7          3.0           5.2          2.3  Iris-virginica
146           6.3          2.5           5.0          1.9  Iris-virginica
147           6.5          3.0           5.2          2.0  Iris-virginica
148           6.2          3.4           5.4          2.3  Iris-virginica
149           5.9          3.0           5.1          1.8  Iris-virginica

[150 rows x 5 columns]

In [4]:
from sklearn.model_selection import train_test_split

In [6]:
X_train, X_test, y_train, y_test = train_test_split(df.drop(['species'], axis='columns'), df['species'], test_size=0.2)

In [22]:
from sklearn.model_selection import KFold
kf = KFold(n_splits=3)
kf

KFold(n_splits=3, random_state=None, shuffle=False)

In [23]:
for train_index, test_index in kf.split([1,2,3,4,5,6,7,8,9]):
    print(train_index, test_index)

[3 4 5 6 7 8] [0 1 2]
[0 1 2 6 7 8] [3 4 5]
[0 1 2 3 4 5] [6 7 8]


In [26]:
from sklearn.model_selection import cross_val_score

In [34]:
cross_val_score(RandomForestClassifier(), df.drop(['species'], axis='columns'), df['species'], cv=3)

array([0.98, 0.94, 0.94])

In [35]:
cross_val_score(SVC(), df.drop(['species'], axis='columns'), df['species'], cv=3)

array([0.96, 0.98, 0.94])

In [39]:
cross_val_score(RandomForestClassifier(n_estimators=40), df.drop(['species'], axis='columns'), df['species'], cv=3)

array([0.98, 0.94, 0.96])